name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.json'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Build debug APK
        run: ./gradlew assembleDebug || echo "No project to build yet"
        working-directory: .

      - name: Upload artifacts (if any)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
